training:
  output_dir: runs/
  batch_size: 32
  weight_decay: 1.0e-12
  num_workers: 0
  trainer_args:
    max_epochs: 3
    accelerator: gpu
    devices: 1
    accumulate_grad_batches: 1
    limit_val_batches: 0.05

  evaluation:
    n_samples: 64 # how many molecules to sample during evaluation
    sample_interval: 1.0 # how often to sample molecules during training, measured in epochs
    val_loss_interval: 0.5 # how often to compute validation set loss during training, measured in epochs

lr_scheduler:
  # to turn off warmup and restarts, set both warmup_length and restart_interval to 0
  base_lr: 1.0e-4
  warmup_length: 0
  restart_interval: 0 # 0 means no restart
  restart_type: 'linear'
  weight_decay: 1.0e-12

checkpointing:
  save_last: True
  save_top_k: 3
  monitor: 'val_total_loss'
  every_n_epochs: 1

wandb:
  project: pharm-gen
  group: "dev"
  name: "dev run"
  mode: online # can be disabled, online, offline

dataset:
  # TODO: no dataset class actually accesses this information
  # data_files: ['/home/elf152/Documents/pharmacoflow/it2_tt_v1.3_0_test0_ph.pkl', '/home/elf152/Documents/pharmacoflow/it2_tt_v1.3_0_test1_ph.pkl', '/home/elf152/Documents/pharmacoflow/it2_tt_v1.3_0_test2_ph.pkl']
  raw_data_dir: 'data/crossdocked_raw/'
  processed_data_dir: 'data/crossdocked_processed'
  # data_files: ['data/crossdocked_pharm_extracted/it2_tt_v1.3_0_test0_ph.pkl.gz']
  # rec_file: 'data/crossdocked_pharm_extracted/receptors.pkl.gz'
  prot_elements: ['C', 'N', 'O', 'S', 'P', 'F', 'Cl', 'Br', 'I', 'B', 'D'] # ['C', 'N', 'O', 'S', 'P', 'F', 'Cl', 'Br', 'I', 'Mg', 'Mn', 'Zn', 'Ca', 'Fe', 'B']
  ph_type_map: [    'Aromatic', 'HydrogenDonor', 'HydrogenAcceptor', 'PositiveIon', 'NegativeIon', 'Hydrophobic']
  pocket_cutoff: 8 # angstroms
  min_pharm_centers: 3
  dataset_size: 200 # used only for debugging
  subsample_pharms: True
  graph_cutoffs: {'pp': 3.5, 'pf': 8, 'fp': 8, 'ff': 9}
  
  
graph:
  graph_cutoffs: {'pp': 3.5, 'pf': 8, 'fp': 8, 'ff': 9}


diffusion:
  n_timesteps: 1000
  precision: 1.0e-5
  pharm_feat_norm_constant: 1
  rl_dist_threshold: 0

dynamics:
  vector_size: 16
  n_convs: 2
  n_hidden_scalars: 128
  message_norm: 'mean'
  dropout: 0.1
  ff_k: 0
  pf_k: 5
  n_message_gvps: 3 # the number of GVPs to chain together for the message function
  n_update_gvps: 2 # the number of GVPs to chain together for the update function
  n_noise_gvps: 4 # the number of GVPs to chain together for the noise prediction block

rec_encoder_loss:
  loss_type: 'optimal_transport' # can be optimal_transport, gaussian_repulsion, hinge, or none